project:
  type: website

website:
  title: "MA705 Project â€“ Adolescent Fertility"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: methods.qmd
        text: Methods
      - href: analysis.qmd
        text: Analysis & Results

format:
  html:
    theme: cosmo
    toc: true
